<?xml version="1.0" encoding="utf-8"?><Database Name="libman4" Class="libmanDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\libman4.mdf;Integrated Security=True" SettingsObjectName="LibraryManager.Properties.Settings" SettingsPropertyName="libman4CS" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorLastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Publisher" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Condition" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Genre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Book_Lending" Member="Lendings" ThisKey="Id" OtherKey="BookId" Type="Lending" />
    </Type>
  </Table>
  <Table Name="dbo.Patrons" Member="Patrons">
    <Type Name="Patron">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Patron_Fee" Member="Fees" ThisKey="Id" OtherKey="PatronId" Type="Fee" />
      <Association Name="Patron_Lending" Member="Lendings" ThisKey="Id" OtherKey="PatronId" Type="Lending" />
      <Association Name="Role_Patron" Member="Role1" ThisKey="Role" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShortDesc" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[Desc]" Member="Desc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Limit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_Patron" Member="Patrons" ThisKey="Id" OtherKey="Role" Type="Patron" />
    </Type>
  </Table>
  <Table Name="dbo.Fee" Member="Fees">
    <Type Name="Fee">
      <Column Name="PatronId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FeeType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="AssessedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PaidDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Patron_Fee" Member="Patron" ThisKey="PatronId" OtherKey="Id" Type="Patron" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lending" Member="Lendings">
    <Type Name="Lending">
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatronId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BorrowDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ReturnDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Book_Lending" Member="Book" ThisKey="BookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
      <Association Name="Patron_Lending" Member="Patron" ThisKey="PatronId" OtherKey="Id" Type="Patron" IsForeignKey="true" />
    </Type>
  </Table>
</Database>